development:
  adapter: mysql2
  encoding: utf8
  database: battleships_server
  pool: 5
  username: root
  password:
  host: 127.0.0.1 

test:
  adapter: mysql2
  encoding: utf8
  database: battleships_server_test
  pool: 5
  username: root
  password:
  host: 127.0.0.1 

production:
  adapter: mysql2
  encoding: utf8
  database: battleships_server
  pool: 5
  username: root
  password:
  host: 127.0.0.1 